# Generated by Django 5.2.7 on 2025-11-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesting_tutor',
            name='subject',
        ),
        migrations.AddField(
            model_name='requesting_tutor',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
